### ISSUE TITLE
Cannot create proposal 

### ISSUE THREAD

**Issue by Febrero** [snapshot-labs/lock#15]
### Expected behavior

Trying to create a new proposal on "CryptoNerds.eth" space (Binance Smart Chain Network). 

The address (0x985A27EC406539F569362D9D5D3681D3A08b5f72) is the owner and has enough tokens to create a new proposal (minimum threshold = 100 CND tokens). 

However, there's a warning stating it needs 100 tokens to create a proposal. The address owns over 100,000 CND tokens.

![image](https://user-images.githubusercontent.com/25055383/121272184-3a743300-c8bd-11eb-80cf-4218d0208228.png)

### Actual behavior

Cannot create proposal. button to publish does not work

### Steps to reproduce the behavior

1. Own 100  CND tokens: https://bscscan.com/address/0x022dbe7fe889fe5353db6d5c63d7dc2c13d38f29 
2. Create new proposal at: https://snapshot.org/#/cryptonerds.eth/create
3. Cannot publish proposal with future dates and block time

**Comment by ChaituVR** [comment]
@Febrero Hi, There is an issue with your space strategy settings, `"decimals": 18` it needs to be `9` according to https://bscscan.com/token/0x022dbe7fe889fe5353db6d5c63d7dc2c13d38f29

Please try changing that and let me know, Thanks

**Comment by ChaituVR** [comment]
I can see it is solved from space now,  closing this.. feel free to reopen, Thanks
