### ISSUE TITLE
Portis wallet error and no longer supported option

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/lock#24]
When connecting with portis we get these error/warning and it's very slow:
![image](https://user-images.githubusercontent.com/51686767/138042556-5ab9dfcb-43e9-4ecf-b16b-f8d7cf4da489.png)

**Comment by ayushkumar63123** [comment]
I found a fix for this on a forum:
async function portisLogin() {
  const portis = new Portis('xxxxx', 'rinkeby')
  try {
      class MoralisPortisProvider {
        async activate() {
          this.provider = portis.provider;
          const MWeb3 = typeof Web3 === 'function' ? Web3 : window.web3;
          this.web3 = new MWeb3(this.provider)
          this.isActivated = true;
          return this.web3;
        }
      }

      // Global Moralis object overwritten
      Moralis.Web3.enable = async () => {
        const web3Provider = new MoralisPortisProvider()
        return await web3Provider.activate()
      };
      window.web3 = await Moralis.enable()
      portis.provider.isTrust = true // NEED TO ADD THIS!!
      const user = await Moralis.authenticate({ provider: portis.provider})
  } catch (error) {
    console.log('authenticate failed', error);
  }
  renderApp();
}
Use the above code for login through portis.

**Comment by ayushkumar63123** [comment]
Please review my solution
