### ISSUE TITLE
Typeerror when canceling wallet login

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/lock#6]
Expected behavior
When canceling a login the account should stop loading.

Actual behavior
When canceling a login the account would stay in loading state.

**Comment by gokaiorg** [comment]
@samuveth I don't have the loader anymore but a svg image instead.
![image](https://user-images.githubusercontent.com/8545464/108165620-72484680-7125-11eb-9def-ae009a4a39c4.png)

**Comment by samuveth** [comment]
Can you try updating your Lock package?

**Comment by gokaiorg** [comment]
@samuveth It's working for me with the update you suggest, if i combine this PR with #9. I tried with all wallets. The loader stop and the Connect Wallet button is back when popin are closed.

**Comment by samuveth** [comment]
@gokaiorg Awesome thanks!

@bonustrack Can we get this merged then?
