### ISSUE TITLE
Brave browser wallet not connecting

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/lock#61]
### Expected behavior
Should be able to connect with Brave browser wallet.

### Actual behavior
Endless spinning loader

### Steps to reproduce the behavior
Download and install brave, setup the wallet and try to connect on snapshot.org

**Comment by mktcode** [comment]
I also experience this:


https://user-images.githubusercontent.com/6792578/182324381-a5963841-8ca9-4bb3-9b7e-27e54ba98e65.mp4

**Comment by samuveth** [comment]
I'm unable to replicate the issue at the moment. However, please feel free to reopen the issue if it persists.

I've also made [changes](https://github.com/snapshot-labs/lock/commit/cd35a108abacbbb3610694555c24fdcf085e0c4f) to add Brave as a injected connector to Lock package.

https://www.loom.com/share/4ce7802adb2b420aa395bd5f0167db6f
